[tool.poetry]
name = "tira-lab"
version = "0.1.0"
description = ""
authors = ["samvancart"]
readme = "README.md"
packages = [{include = "tira_lab"}]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
