version: '2.1'
orbs:
  python: circleci/python@3.8.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run pytest src
          name: Test it
workflows:
  main:
    jobs:
      - build