version: '2.1'
orbs:
  python: circleci/python@1.0.0
  codecov: codecov/codecov@3.2.2
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests and get coverage
          command: |
            poetry run pytest src
      - codecov/upload
          
workflows:
  main:
    jobs:
      - build
          